### ISSUE TITLE
Crash für MAX Cube

### ISSUE THREAD

**Issue by gunkie** [erdoking/check_fhem#1]
https://github.com/erdoking/mk_fhem/blob/aa70c278ff0087b10551c51c740ea80e191e0320/local/share/check_mk/checks/fhem#L94

Hallo erdoking,

ich hab einen MAX Cube. Der Agent erzeugt dafür folgende Ausgabe:
WT_Wohnzimmer                             WT_Wohnzimmer                    TYPE                 MAX
                     2018-10-09 21:38:53  WT_Wohnzimmer                    MAXLAN_error         0
                     2018-10-09 21:38:53  WT_Wohnzimmer                    MAXLAN_errorInCommand
                     2018-10-09 21:38:53  WT_Wohnzimmer                    MAXLAN_initialized   1
                     2018-10-09 21:38:53  WT_Wohnzimmer                    MAXLAN_isAnswer      0
                     2018-10-09 21:38:53  WT_Wohnzimmer                    MAXLAN_valid         1
                     2018-10-09 21:38:53  WT_Wohnzimmer                    battery              ok
                     2018-10-09 15:37:12  WT_Wohnzimmer                    boostDuration        5
                     2018-10-09 15:37:12  WT_Wohnzimmer                    boostValveposition   80

In der Zeile mit MAXLAN_errorIn Command steht kein Wert! Deshalb crashed der Check hier. 
Ich habe das bei mir lokal folgendermaßen geändert:
  if len(line)>4:
        data[line[3]]['value']=line[4]
  else:
        data[line[3]]['value']=''

Das scheint bei mir zunächst zu funktionieren - wäre mir da aber nicht so sicher ...

Danke für das Klasse Plugin!

Gunkie

**Comment by erdoking** [comment]
Hi Gunkie,

das Problem der leeren Readings hatten wir bereits im FHEM-Forum diskutiert, allerdings ist das Thema im Sand verlaufen.

Die Idee dahinter war den Agent so anzupassen, das leere Readings erst gar nicht gesendet werden.
https://forum.fhem.de/index.php/topic,63723.msg813549.html#msg813549

Könntest du bitte testen ob das Problem verschwindet wenn du folgende Zeile im Agent anpasst:

Zeile 77:
```
if ( "$reading" !~ /RegL_\d+/) {
ersetzen durch
if (( "$reading" !~ /RegL_\d+/) and( "$reading" ne "" )) {
ODER
if (( "$reading" !~ /RegL_\d+/) and( "$reading" ne " " )) {
```

Möglicherweise werden leere Readings auch als Leerzeichen zurückgegeben?!
Wenn das nicht helfen sollte würde ich dich um einen (gerne auch anonymisierten :) ) Abzug bitten

`/opt/fhem/fhem.pl 7072 "jsonlist2 TYPE=.*:FILTER=state=..*:FILTER=model!=CCU-FHEM:FILTER=model!=ActionDetector" > /tmp/fhem_output.txt `

Wichtig -> bitte original-Datei übergeben da beim kopieren gerne Leerezeichen abhanden kommen oder 'umstrukturiert' werden

Grüße
erdo

**Comment by gunkie** [comment]
Hi erdo,

Danke für die schnelle Hilfe.

Hat so nicht funktioniert, habe dann aber den Wert verglichen:

`if (( "$reading" !~ /RegL_\d+/) and( "$devices{$device}{$channel}{Readings}{$reading}{Value}" ne "")) {`

Das funktioniert und der Wert ist echt leer und kein Leerzeichen. Ein trim vor dem Vergleich wäre noch schöner, aber das übersteigt meine Perl-Kenntnisse...

Gibt es eine Möglichkeit einen Ausgefallenen Themostat in check_mk zu bemerken? Wenn ich z.B. die Batterie herausnehme gibt es in FHEM kurz einen Fehler aber in check_mk mekre ich davon nichts.

Grüße,
Gunkie

**Comment by erdoking** [comment]
Zu dem Thermostat:
Bitte neues Issue mit mehr details (zB Hersteller+Model) anlegen.

Zu dem eigentlichem Thema:

Man sollte auch echt die Value anstatt des Variablenames prüfen *kopfauftischhau*
Danke für dein debugging!

Ich habe das nun wie folgt umgesetzt, kannst du das bitte einmal testen, dann fließt das in den Quellcode ein.
Meine FHEM-Geräte sind (leider) zu sauber ;)

```
        foreach my $channel (sort keys %{$devices{$device}}){
                ## get device readings  
                foreach my $reading (sort keys %{$devices{$device}{$channel}{Readings}}){

                        ## trim value
                        my $value = "$devices{$device}{$channel}{Readings}{$reading}{Value}";
                        $value =~ s/^\s+|\s+$//g;

                        if (( "$reading" !~ /RegL_\d+/ ) and ( "$value" ne "" )) {
                                ## e.g: $devices{eg.wz.thermostat}{Readings}{model} = HM-SEC-SCo
                                printf("%-20s %-20s %-30s   %-20s %s\n","", $devices{$device}{$channel}{Readings}{$reading}{Time}, $channel, $reading, $value);
                        }
                }
        }
```

Grüße
erdo

**Comment by gunkie** [comment]
Zum Tisch:
der kann nichts dafür und Du musst ihn nicht mit Deinem Kopf schlagen.

Zum Thermostat: 
In FHEM scheine ich auch keine vernünftige Aussage zu bekommen. Ich mach mich erst mal schlau ...

Zum Thema:
Dein Vorschlag funktioniert bei mir. Ich bekomme keine Fehler mehr.

Danke und Grüße,
Gunkie

**Comment by erdoking** [comment]
Anpassung am Agent in Code übernommen.
Wird im nächstem Release aufgenommen.

Commit: https://github.com/erdoking/mk_fhem/commit/9342492277a04befd1d3622b43664bb5128da490
