### ISSUE TITLE
HomeMatic-Devices werden nicht mehr erkannt

### ISSUE THREAD

**Issue by f-zappa** [erdoking/check_fhem#3]
Moin, nach einem FHEM-Update sind bei mir alle HomeMatic-Devices aus dem Monitoring geflogen. Inzwischen habe ich herausgefunden, dass diese wohl ihren TYPE geändert haben und nicht mehr "CUL" heißen sondern "CUL_HM". Dadurch werden sie direkt schon im Plugin für den Agenten weggefiltert.

Abhilfe: "CUL_HM" zu den @allowed_types hinzufügen (mk_fhem Zeile 13):
my @allowed_types = ( 'speedtest', 'CUL_HM', 'CUL', 'JeeLink', 'TRAFFIC', 'WifiLight', 'harmony', 'XiaomiFlowerSens', 'XiaomiBTLESens' );

Erdo,  magst du direkt hier den Code anpassen? Danach kann der Issue schon wieder zu :-)

**Comment by erdoking** [comment]
Moin f-zappa,

Top danke für den Hinweis! 
Ich habe ein neues (Hotfix-)Release gebaut und (hoffentlich) alle offenen Punkte berücksichtigt. 

Grüße
erdo
